# see: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

variables:
  POSTGRES_DB: "vault"
  POSTGRES_USER: "vault"
  POSTGRES_PASSWORD: "vault"
  VAULT_POSTGRES_HOST: "postgres"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  ENV: CI # run Makefile in CI mode
  PYTEST_REPORT: pytest.xml
  PYLINT_REPORT: pylint.json

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - venv/

services:
- postgres:10

image:
  name: python:3.8

before_script:
  - python --version
  - pip install virtualenv

test:
  stage: test
  # job can be preempted by subsequent requests to re-run
  # https://git.archive.org/help/ci/yaml/README.md#interruptible
  interruptible: true
  script:
  - make setup
  - make test
  - make lint
  - make ck-format
  artifacts:
    reports:
      junit: $PYTEST_REPORT
      codequality: $PYLINT_REPORT
      cobertura: coverage.xml

qa-deploy:
  stage: deploy
  variables:
    ENV: qa
    GIT_REF: $CI_COMMIT_BRANCH
    PLAYBOOK: setup_vault_site.yml
  trigger:
    project: archive-it/ait-ansible
    branch: master
    strategy: depend
  rules:
   # Run this job when commits are pushed or merged to the default branch
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $ENABLE_CD == 'true'
