---
# We would need to install apache 
# Then copy config files ..

- name: install /etc/ait.yml
  become_user: root
  become: true
  template: src=templates/vault.yml.j2 dest=/etc/vault.yml

# Waiting for apache till all the connections are drained and then restarting it
# - name: wait until apache2 connections are drained.
#   wait_for:
#    host: 0.0.0.0
#    port: 80
#    state: drained

# Note fetching will fail if there are local changes to /opt/DPS/vault-site
# as force option is no by default in ansible.builtin.git
- name: Fetch Vault Site
  become_user: root
  become: yes
  git:
    repo: 'git@git.archive.org:dps/vault-site.git'
    dest: /opt/DPS/vault-site
    version: 'master'

- name: Creating venv and install requirements.txt
  become: true
  become_user: root
  pip:
    requirements: /opt/DPS/vault-site/requirements.txt
    virtualenv: /opt/DPS/vault-site-env
    virtualenv_command: /usr/bin/python3.8 -m venv

- name: restart apache2
  service: name=apache2 state=restarted
  become: true
  become_user: root
