---
# We would need to install apache 
# Then copy config files ..

- name: install /etc/ait.yml
  become_user: root
  become: true
  template: src=templates/vault.yml.j2 dest=/etc/vault.yml

# Waiting for apache till all the connections are drained and then restarting it
# - name: wait until apache2 connections are drained.
#   wait_for:
#    host: 0.0.0.0
#    port: 80
#    state: drained

- name: Fetch Vault Site
  become_user: root
  become: yes
  git:
    repo: 'git@git.archive.org:dps/vault-site.git'
    dest: /opt/DPS/vault-site
    version: 'master'
  notify:
  - restart apache2
