- name: restart process_chunked_files
  service:
    name: process_chunked_files
    state: restarted
  become: true

- name: disable process_hashed_files
  service:
    name: process_hashed_files
    state: stopped
    enabled: no
  become: true
