- name: restart process_chunked_files
  service:
    name: process_chunked_files
    state: restarted
  become: true

- name: restart process_hashed_files
  service:
    name: process_hashed_files
    state: restarted
  become: true