- name: restart process_chunked_files
  svc:
    name: process_chunked_files
    state: restarted
    service_dir: /etc/service
  become: true

- name: restart process_hashed_files
  svc:
    name: process_hashed_files
    state: restarted
    service_dir: /etc/service
  become: true
