# Generated by Django 3.2.3 on 2021-06-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="mismatch_count",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
