# Generated by Django 3.2.3 on 2021-06-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('collection', 'client_filename', 'staging_filename', 'sha256_sum'), name='unique_file'),
        ),
    ]
