# Generated by Django 3.2.3 on 2021-06-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0007_auto_20210611_1811"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="avg_replication",
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
