# Generated by Django 3.2.3 on 2021-09-07 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0011_alter_organization_quota_bytes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("UPLOADED", "Uploaded"),
                            ("HASHED", "Hashed"),
                            ("REPLICATED", "Replicated"),
                        ],
                        default="REGISTERED",
                        max_length=50,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("hashed_at", models.DateTimeField(blank=True, null=True)),
                ("replicated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vault.collection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vault.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow_identifier", models.CharField(max_length=255)),
                ("name", models.TextField()),
                ("relative_path", models.TextField()),
                ("size", models.PositiveBigIntegerField()),
                ("type", models.CharField(blank=True, max_length=255)),
                (
                    "original_last_modified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("UPLOADED", "Uploaded"),
                            ("HASHED", "Hashed"),
                            ("REPLICATED", "Replicated"),
                        ],
                        default="REGISTERED",
                        max_length=50,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("hashed_at", models.DateTimeField(blank=True, null=True)),
                ("replicated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deposit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="vault.deposit",
                    ),
                ),
            ],
        ),
    ]
