# Generated by Django 3.2.3 on 2021-09-08 07:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0014_adding_triggers_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="treenode",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treenode",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treenode",
            name="deletion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treenode",
            name="file_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="treenode",
            name="md5_sum",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9]{32}$", "only hex-encoded md5 hashes are allowed"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="treenode",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="treenode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("FILE", "File"),
                    ("FOLDER", "Folder"),
                    ("COLLECTION", "Collection"),
                    ("ORGANIZATION", "Organization"),
                ],
                default="FILE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="treenode",
            name="sha1_sum",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9]{40}$", "only hex-encoded sha1 hashes are allowed"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="treenode",
            name="sha256_sum",
            field=models.CharField(
                default="000000",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9]{64}$",
                        "only hex-encoded sha256 hashes are allowed",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="treenode",
            name="size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="treenode",
            name="staging_filename",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treenode",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treenode",
            name="uploaded_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
