# Generated by Django 3.2.3 on 2021-09-09 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0015_auto_20210908_0746"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treenode",
            old_name="deletion_date",
            new_name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="treenode",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="treenode",
            name="modified_date",
        ),
        migrations.RemoveField(
            model_name="treenode",
            name="staging_filename",
        ),
        migrations.RemoveField(
            model_name="treenode",
            name="uploaded_date",
        ),
        migrations.AddField(
            model_name="treenode",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="treenode",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="treenode",
            name="user_modified_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="treenode",
            name="sha256_sum",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9]{64}$",
                        "only hex-encoded sha256 hashes are allowed",
                    )
                ],
            ),
        ),
    ]
