# Generated by Django 3.2.3 on 2021-09-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0016_auto_20210909_1058"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treenode",
            old_name="user_modified_date",
            new_name="pre_deposit_modified_at",
        ),
    ]
