# Generated by Django 3.2.3 on 2021-09-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0017_auto_20210913_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="tree_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vault.treenode",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tree_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vault.treenode",
            ),
        ),
    ]
