# Generated by Django 3.2.3 on 2021-09-20 21:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0018_orgs_colls_reference_treenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='parent',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vault.treenode'),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='pre_deposit_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='sha256_sum',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{64}$', 'only hex-encoded sha256 hashes are allowed')]),
        ),
        migrations.AddConstraint(
            model_name='treenode',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='vault_treenode_parent_and_name'),
        ),
    ]
