# Generated by Django 3.2.3 on 2021-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0020_nullable_treenode_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositfile',
            old_name='original_last_modified_at',
            new_name='pre_deposit_modified_at',
        ),
    ]
