# Generated by Django 3.2.3 on 2021-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0023_auto_20210923_2221"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="pbox_collection",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
