# Generated by Django 3.2.3 on 2021-11-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0026_remove_treenode_auto_uploaded_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treenode",
            old_name="pbox_item",
            new_name="pbox_path",
        ),
    ]
