# Generated by Django 3.2.3 on 2021-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0027_rename_treenode_pbox_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="state",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered"),
                    ("UPLOADED", "Uploaded"),
                    ("HASHED", "Hashed"),
                    ("REPLICATED", "Replicated"),
                    ("COMPLETE_WITH_ERRORS", "Complete With Errors"),
                ],
                default="REGISTERED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="depositfile",
            name="state",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "Registered"),
                    ("UPLOADED", "Uploaded"),
                    ("HASHED", "Hashed"),
                    ("REPLICATED", "Replicated"),
                    ("ERROR", "Error"),
                ],
                default="REGISTERED",
                max_length=50,
            ),
        ),
    ]
