# Generated by Django 3.2.9 on 2022-02-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0028_add_deposit_error_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="treenode",
            name="deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
