# Generated by Django 3.2.9 on 2022-02-25 00:07

"""Adds trigger asserting that updated TreeNodes cannot be assigned NULL
path.
"""

from django.db import migrations

SQL = """
CREATE OR REPLACE FUNCTION _reject_null_treenode_path() RETURNS TRIGGER AS
$$
BEGIN
    IF NEW.path IS NULL THEN
        RAISE EXCEPTION 'path may not be updated to NULL';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- assert modified rows can't set path to NULL
DROP TRIGGER IF EXISTS treenode_path_prevent_null_trg ON vault_treenode;
CREATE TRIGGER treenode_path_prevent_null_trg
    BEFORE UPDATE ON vault_treenode
    FOR EACH ROW
    WHEN (NEW.path IS NULL)
    EXECUTE PROCEDURE _reject_null_treenode_path();
"""


REVERSE_SQL = """
DROP TRIGGER IF EXISTS treenode_path_prevent_null_trg ON vault_treenode;
DROP FUNCTION IF EXISTS _reject_null_treenode_path();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0029_adds_treenode_deleted"),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=REVERSE_SQL,
        ),
    ]
