# Generated by Django 3.2.9 on 2022-03-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0030_refreshes_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="report_json_version",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
